### ISSUE TITLE
同学，请问你是clone了什么源代码嘛？有些路径有问题

### ISSUE THREAD

**Issue by yuchen202** [Robin-WZQ/Chinese-Landscape-Painting-generation#1]
/hy-tmp/stable-diffusion，这个路径没有看明白，是clone一下stable diffusion嘛

**Comment by Robin-WZQ** [comment]
嗯嗯对的

**Comment by yuchen202** [comment]
同学，请问clone的源代码地址能发一下嘛，谢谢


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月10日(周四) 晚上6:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Robin-WZQ/Text-Guide-Chinese-Landscape-Painting-Generation] 同学，请问你是clone了什么源代码嘛？有些路径有问题 (Issue #1)




 
嗯嗯对的
 
&mdash;

**Comment by Robin-WZQ** [comment]
https://github.com/justinpinkney/stable-diffusion.git
